version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - app_data:/app/public/system
    env_file: .env
    environment:
      RAILS_ENV: development

  database:
    image: postgres:12.1
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  app_data:
  db_data: